export const {
  PORT,
  MONGO_URI,
  JWT_SECRET,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  EMAIL_USER,
  EMAIL_PASS,
  ADMIN_EMAIL,
  ADMIN_PASSWORD,
  HR_EMAIL,
  HR_PASSWORD,
  FRONTEND_URL
} = process.env;
